# Generated by Django 5.2.16 on 2026-07-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Nuru Massage', 'Nuru Massage'), ('Swedish Massage', 'Swedish Massage'), ('Deep Tissue Massage', 'Deep Tissue Massage'), ('Lingam Massage', 'Lingam Massage'), ('Lymphatic Drainage', 'Lymphatic Drainage'), ('Thai Massage', 'Thai Massage'), ('Tantric Massage', 'Tantric Massage'), ('Ashiatsu Massage', 'Ashiatsu Massage'), ('Jacuzzi Treatment', 'Jacuzzi Treatment'), ('Massage & Happy Ending', 'Massage & Happy Ending')], max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(max_length=50)),
                ('hear_about', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
